---
# settings
esphome:
  name: alexs-bedroom-bluetooth-proxy
  friendly_name: "Alex's Bedroom Bluetooth Proxy"

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: "192.168.2.171"
  domain: ".iot"
  on_connect:
    then:
      - light.turn_on:
          id: status_led
          red: 0%
          green: 100%
          blue: 0%
          brightness: 100%
          effect: none

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# configuration
light:
  - platform: esp32_rmt_led_strip
    id: status_led
    chipset: WS2812
    pin: 35
    num_leds: 1
    rgb_order: GRB
    internal: true

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    interval: 320ms
    window: 320ms
    active: false
