---
# settings
esphome:
  name: gas-meter
  friendly_name: "Gas Meter"

packages:
  meter: github://tronikos/esphome-magnetometer-water-gas-meter/esphome-gas-meter.yaml@main

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: "192.168.2.182"
  domain: ".iot"

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# configuration
sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

substitutions:
  volume_unit: "m³"
  i2c_scl: "GPIO22"
  i2c_sda: "GPIO19"
  hide_magnetic_field_strength_sensors: "true"
  hide_half_rotations_total_sensor: "true"
