---
substitutions:
  system_name: gas-meter
  friendly_name: Gas Meter
  device_description: ESP32 magnetometer-based gas meter
  volume_unit: "m³"
  i2c_scl: "GPIO22"
  i2c_sda: "GPIO19"
  hide_magnetic_field_strength_sensors: "true"
  hide_half_rotations_total_sensor: "true"

packages:
  device: !include
    file: esp32/base.yaml
  meter: github://tronikos/esphome-magnetometer-water-gas-meter/esphome-gas-meter.yaml@main
