---
substitutions:
  system_name: konnected-alarm-panel
  friendly_name: Konnected Alarm Panel
  device_description: Konnected Alarm Panel Pro
  name: konnected-alarm-panel

packages:
  device: !include
    file: esp32-ethernet/base.yaml
  konnected.alarm-panel-pro-ethernet: github://konnected-io/konnected-esphome/alarm-panel-pro-v1.8-ethernet.yaml@master

esphome:
  name_add_mac_suffix: false

# remove unused components
web_server: !remove
mdns: !remove
button: !remove

# configuration
sensor:
  - id: !remove uptime_sensor

binary_sensor:
  - id: !extend zone1
    name: Shed Motion Sensor
    device_class: motion

  - id: !extend zone2
    name: Hall Motion Sensor
    device_class: motion

  - id: !extend zone3
    name: Office Motion Sensor
    device_class: motion

  - id: !extend zone4
    name: Living Room Motion Sensor
    device_class: motion

  - id: !extend zone5
    name: Master Bedroom Motion Sensor
    device_class: motion

  - id: !remove zone6 # does not work

  - id: !extend zone7
    name: Lounge Motion Sensor
    device_class: motion

  - id: !extend zone8
    name: Front Door Contact Sensor
    device_class: door

  - id: !extend zone9
    name: Laundry Door Contact Sensor
    device_class: door

  - id: !remove zone10
  - id: !remove zone11
  - id: !remove zone12
