---
# settings
esphome:
  name: living-room-ac
  friendly_name: Living Room AC
esp8266:
  board: nodemcuv2
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.2.225
  domain: .iot

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# configuration
remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%

sensor:
  - platform: homeassistant
    name: "House Heater Temperature"
    entity_id: sensor.ac_living_temperature
    id: ac_living_temperature
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

climate:
  - platform: coolix
    name: "Living Room AC"
    sensor: ac_living_temperature
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
