---
substitutions:
  system_name: living-room-ac
  friendly_name: Living Room AC
  device_description: NodeMCU-based Coolix IR controller

esp8266:
  restore_from_flash: true

packages:
  device: !include
    file: esp8266/base.yaml

# configuration
remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%

sensor:
  - platform: homeassistant
    name: "House Heater Temperature"
    entity_id: sensor.ac_living_temperature
    id: ac_living_temperature
    internal: true

climate:
  - platform: coolix
    name: "Living Room AC"
    sensor: ac_living_temperature
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
