---
substitutions:
  system_name: office-bluetooth-proxy
  friendly_name: Office Bluetooth Proxy
  device_description: M5Stack AtomS3 Bluetooth proxy

esp32:
  board: m5stack-atoms3

packages:
  device: !include
    file: esp32/base.yaml
  bluetooth-proxy: !include
    file: esphome-common/bluetooth-proxy.yaml
