---
# settings
esphome:
  name: shed-ac
  friendly_name: Shed AC
esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.2.9
  domain: .iot

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# configuration
remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%

sensor:
  - platform: dht
    model: AM2302
    pin: D2
    temperature:
      name: "Shed AC Temperature"
      id: temperature
    humidity:
      name: "Shed AC Humidity"
      id: humidity
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

climate:
  - platform: coolix
    id: shed_ac_coolix
    name: "Shed AC"
    sensor: temperature
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
