---
substitutions:
  system_name: shed-ac
  friendly_name: Shed AC
  device_description: NodeMCU-based Coolix IR controller with DHT sensor

packages:
  device: !include
    file: esp8266/base.yaml

# configuration
remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%

sensor:
  - platform: dht
    model: AM2302
    pin: D2
    temperature:
      name: "Shed AC Temperature"
      id: temperature
    humidity:
      name: "Shed AC Humidity"
      id: humidity
    update_interval: 60s

climate:
  - platform: coolix
    id: shed_ac_coolix
    name: "Shed AC"
    sensor: temperature
    visual:
      min_temperature: 17 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
